#define MOD_OUTPUT	0
#define MOD_LOSING	1
#define SFX_AMBULANCE	33
#define MOD_LEVEL3	2
#define MOD_OUTPUT2	3
#define MOD_FLATOUTLIES	4
#define MOD_LEVEL1	5
#define SFX_BOOM	129
#define MOD_VICTORY	6
#define MOD_LEVEL2	7
#define MOD_OUTPUT3	8
#define MSL_NSONGS	9
#define MSL_NSAMPS	194
#define MSL_BANKSIZE	203
