#define MOD_MUSIC6	0
#define MOD_JAPA2	1
#define MOD_JAPAO	2
#define MOD_MUSIC43K	3
#define MOD_AGORAFOI	4
#define SFX_AMBULANCE	124
#define MOD_FASE11	5
#define SFX_BOOM	156
#define MOD_FLATOUTLIES	6
#define MOD_FASE2	7
#define MSL_NSONGS	8
#define MSL_NSAMPS	219
#define MSL_BANKSIZE	227
