#define MOD_OUTPUT	0
#define SFX_AMBULANCE	2
#define MOD_LEVEL3	1
#define MOD_OUTPUT2	2
#define MOD_FLATOUTLIES	3
#define MOD_LEVEL1	4
#define SFX_BOOM	98
#define MOD_LEVEL2	5
#define MOD_OUTPUT3	6
#define MSL_NSONGS	7
#define MSL_NSAMPS	132
#define MSL_BANKSIZE	139
